# Generated by Django 3.2.19 on 2023-05-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejemplos', '0009_egreso_productosegreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasEncabezado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('no_factura', models.CharField(max_length=100)),
                ('fecha_factura', models.DateField()),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasDetall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdenCompras.comprasencabezado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.producto')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compra',
            },
        ),
    ]
