# Generated by Django 3.2.19 on 2023-05-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdenCompras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasencabezado',
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='ComprasDetall',
        ),
        migrations.DeleteModel(
            name='ComprasEncabezado',
        ),
    ]
